### ISSUE TITLE
fsync() or FlushFileBuffers() needed before backup?

### ISSUE THREAD

**Issue by chickenandpork** [jorgenpt/rugs#15]
Hey, More of a question than issue.

I'm hoping to backup the RUGS database on a regular basis, but I think there's a race-condition, and I don't know if I'm interpreting the code correctly.

 in reference to #14 , this is optimistic about any writes, right?  I don't see indication that RUGS sync()s the backing file after writes.  If that's true, then an unsync'd file might have write in-flight, so a backup might miss the most recent changes.

Have I missed where this is protected?  Is, for example, the `await` on line 236 of handlers.rs actually awaiting a sync() ?

Thanks!

**Comment by jorgenpt** [comment]
Hi @chickenandpork, I think you’re right. There’s no fsync that should be added though, as we rely on SQLite for our persistence. I recently had to address this in some other software at work — SQLite has a backup command that safely creates atomic copies of the database. 

I’ll need to test, but you can either trigger it within RUGS using the API, or I believe you can do something like this using the CLI SQLite tool, and then backup backup.db instead: 

`sqlite3 source.db ".timeout 600" ".backup backup.db"`

I will need to verify before I update the instructions.

**Comment by chickenandpork** [comment]
> I’ll need to test, but you can either trigger it within RUGS using the API, or I believe you can do something like this using the CLI SQLite tool...

thanks!

My use-case: I wanted to sync/quiesce the data store long enough for a (quick-reacting) AWS snapshot to be taken of the filesystem mounted at /data.  I found that the `VACUUM TO` method of defragging to an alternative file has some complexity of moving it back -- or Vacuuming to a mounted filesystem which mimics the live file sys mounted at /live and can take its place if needed.

Being able to quiesce-and-snap seems more straight-forward, but it would require an API call to post a quiesce with a timeout: `POST /api/sync?delay=3` or such.  I was considering adding a read-lock/sleep/release flow as a handled method.

**Comment by jorgenpt** [comment]
@chickenandpork Hm, interesting. I'm not sure if there's a good API for SQLite to have it flush any pending work. If not, you might need to e.g. call `.close().await` on the pool and re-open it after the quiescence? Or you could shut down the server process, do the backup, then start the server, if that's an option.

FWIW, the SQLite database is opened with default `FULL` synchronous mode (https://www.sqlite.org/pragma.html#pragma_synchronous), which does seem to indicate that it relies on filesystem flushes to make sure it's in a good state after a write. So it's possible this'll work fine without quiescence?

**Comment by chickenandpork** [comment]
> @chickenandpork Hm, interesting. I'm not sure if there's a good API for SQLite to have it flush any pending work. If not, you might need to e.g. call `.close().await` on the pool and re-open it after the quiescence? Or you could shut down the server process, do the backup, then start the server, if that's an option.

There's some old write-ups of using a read-lock or a write-lock to quiesce the DB, do the backup, and on close, the lock is released.  There was apparently a way through the SQLite CLI but I don't remember anymore. 
> 
> FWIW, the SQLite database is opened with default `FULL` synchronous mode

This is actually good news -- I had to look it up, but I believe this means that writes are sync() to the disk before continuing which suggests always a safe datafile.

I'm going to go forward with that.

@jorgenpt I really appreciate your advice, and the generosity to reply in such detail.

Thanks!

**Comment by jorgenpt** [comment]
@chickenandpork Please let me know how it works! It would be great to document your method of live backups for AWS users, as I suspect that's a common case. :)

**Comment by chickenandpork** [comment]
> @chickenandpork Please let me know how it works! It would be great to document your method of live backups for AWS users, as I suspect that's a common case. :)

Would be nice, but I suddenly find myself generating a resume. I don't have access to what I put together, and I'd need to sanitize it and get permissions to share.

For anyone relating my work:

1. I found that AWS EFS doesn't offer the responsiveness required: it seems to allocate bandwidth and responsiveness from size of data at-rest, and the data's small, so I was seeing 30s response times alerting into the log.  AWS support wanted a bunch of data collection before advising, and I was hounded to deploy a thing, so I switches to EBS
2. EBS is a bit more straight-forward, but in an ECS config, EBS is mounted to the host, not the container, and is specific to an AZ not a region (so "us-west-1a" not "us-west-1").
3. really, no end of issues and hidden gotchas: if you can stomach the hidden cost of USD75/mo for the controller, go with AWS EKS: it mounts the EBS to the container, not the host, but still suffers from EBS having limited cross-region capability
4. Data Lifecycle Management was trivial due to the conversation above (and working fine)

Sorry folks.
