### ISSUE TITLE
Further updates

### ISSUE THREAD

**Issue by KaosSpectrum** [jorgenpt/rugs#3]
Any chance to get further updates like build information, etc?

**Comment by jorgenpt** [comment]
@KaosSpectrum If you mean things like comments, votes, etc, then yes! This week I was just thinking about putting in some time to get that working. It looks like it would be straight forward.

**Comment by KaosSpectrum** [comment]
That's cool, i am just setting up perforce (moving from Plastic), and we use Linux, so this seems like a way to keep Linux without needing to setup IIS for the Epic meta server

**Comment by jorgenpt** [comment]
@KaosSpectrum It should be implemented in commit 948949f8c2058e661e1a1484c9fed3ac14c6568e -- I'll deploy it at work on Monday, but it seemed to work fine in my local testing. Please open an issue if you have any trouble with it!

**Comment by jorgenpt** [comment]
@KaosSpectrum I've deployed what's tagged as v0.3.2 at work after addressing a few issues, FYI. So if you've deployed 0.3 or 0.3.1, you might want to upgrade.
